version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config:/mosquitto/config
      - ./etc:/etc/mosquitto
      - ./log:/mosquitto/log
      - type: volume
        source: data
        target: /mosquitto/data

volumes:
  data:
    name: "mosquitto-data"
